### ISSUE TITLE
Create Feed API 수정 요청 (ProfileService의 save() 수정 요청)

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#116]
### 문제사항 : 프로필 생성시 배경 이미지를 설정하지 않았는데, 배경 이미지 피드가 만들어지는 문제 발생

<image src="https://user-images.githubusercontent.com/43838030/154598869-991b41af-1ff0-469e-b266-342ecaf3451a.png"/>

피드는 이미지를 보기 위한 사진첩 역할의 기능입니다. 따라서 이미지가 null일 경우 피드 아이템이 생성되면 안될 것 같습니다 😢

따라서, ProfileService.java의 save 메소드에서, saveBackgroundImageToFeed 메소드를 호출하기 전에 ProfileRequest 의  imageUrl, bgImageUrl 가 null 일 경우 해당 함수를 호출하지 않도록 해주시면 감사하겠습니다.

## Todo
- [x] 이슈확인
- [ ] null check 추가

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
`null`인 경우, `saveImageToFeed`와 `saveBackgroundImageToFeed`함수에서 확인하여 피드로 저장하지 않고 있습니다.

**Comment by vo0a** [comment]
앗 그러네요. 안드로이드에서 bgImageUrl 없을 경우 "" 로 request 로 보낸다면, isEmpty() 로도 처리해야 feed 가 정상적으로 안 만들어질 것 같고, null 로 보내고 있다면 백엔드에는 문제 없어보입니다!

**Comment by paksuua** [comment]
클라이언트단에서 ""로 보내서 생성된 것으로 확인했습니다 현재 수정 후 테스트 완료했습니다. 죄송합니다 이슈 종료하겠습니다🙏
