### ISSUE TITLE
Feed image lock update API 수정 요청

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#36]
## Description
클라이언트에서 Feed image lock update 요청 후 변경 결과에 따라 UI를 업데이트 하기 위해서 response에 해당 피드 아이템의 데이터 변경 결과를 보내주시면 감사하겠습니다.

## Todo
- [x]  Feed image lock update API response data에 Feed 데이터(1개 객체) 추가
- [x] 클라이언트에게 다했다고 자랑하기

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
네 변경하였습니다. 추가로 API 명세서도 업데이트했습니다 :)
