### ISSUE TITLE
Profile Update, Feed API 수정 요청

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#38]
## Description
특정 프로필의 피드는 해당 프로필의 변경된 프로필, 배경 이미지의 히스토리 기능임
현재 프로필을 업데이터 하더라도 피드에 데이터가 추가되지 않음

## Todo
- [x] 이슈 확인

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
넵 로직 추가하였습니다.
