### ISSUE TITLE
채팅방 내 파일 리스트 조회 api 명세서 수정 요망

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#39]
## Description
![Screen Shot 2022-02-05 at 20 41 16 PM](https://user-images.githubusercontent.com/62296097/152640594-d1571447-684f-4371-ba10-98db4ca491a1.png)
title 과 extension의 Type이 Object List -> String 인 것 같습니다 

## Todo
- [x] title 과 extension의 Type 확인

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
수정 완료!! 😎😎😎
[채팅방 내 파일 리스트 조회 API 명세서](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/채팅방-내-파일-리스트-조회)
