### ISSUE TITLE
채팅방 수정 API 명세서 수정 요망

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#40]
## Description
![Screen Shot 2022-02-05 at 21 02 06 PM](https://user-images.githubusercontent.com/62296097/152641227-92a2b754-ca4d-4090-a99b-407920601096.png)
Path Variable에 대해서 작성이 빠져있습니다

## Todo
- [x] Path Variable 추가하기

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
네 추가했습니다~!
[채팅방 수정 API 명세서](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/채팅방-수정)
