### ISSUE TITLE
채팅방 조회 api 명세서 수정 요망

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#41]
## Description
내 자신에 해당하는 유저의 profileImage를 가져올 때 type이 String List가 아닌 String인 것 같습니다.

## Todo
- [ ] profileImage의 Type String List -> String 으로 수정

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
@014967 넵 API 명세서 수정했습니다. 꼼꼼하게 확인해주셔서 감사합니다!🤗
