### ISSUE TITLE
Fcm Device Token 저장 API 요망

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#46]
## Description
유저의 fcm device token를 저장할 수 있도록, API 를 구현하길 희망합니다.

## Todo
- [ ] API request body에 deviceToken Field 추가 

## ETC
기타사항

**Comment by vo0a** [comment]
FCM device token 저장 완료하고 cur_max_message_id 갱신하는 API 도 추가하였습니다.
