### ISSUE TITLE
채팅방 리스트 조회 api 수정 

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#53]
## Description
채팅방 리스트를 가져올 때, 1:1 채팅방인데 유저 자신의 프로필이 포함되어 1:N 채팅방처럼 보이는 이슈가 있습니다.
유저 본인의 썸네일을 제외한 나머지 채팅방 참가자들의 프로필을 전해주시면 감사하겠습니다

## Todo
- [x] 채팅방 리스트 API response field userChatrooms 수정 
## ETC
기타사항

**Comment by SuyeonChoi** [comment]
채팅방 제목에 대해서도 동일한 이슈 발생 예상
