### ISSUE TITLE
Profile Get API 에러 질문 

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#58]
## Description
유저 로그인 후 profile get 요청 시 500 에러가 날아오며 서버 콘솔에 다음과 같은 로그가 찍힘

Server log
`[Internal Server Exception]org.springframework.orm.jpa.JpaSystemException: Error attempting to apply AttributeConverter; nested exception is javax.persistence.PersistenceException: Error attempting to apply AttributeConverter`
<img width="1372" alt="스크린샷 2022-02-09 오후 1 44 49" src="https://user-images.githubusercontent.com/43838030/153123515-7b89761e-a33d-4571-9151-6e4b915b6b56.png">

Client log
![스크린샷 2022-02-09 오후 1 45 23](https://user-images.githubusercontent.com/43838030/153123554-d9c0fddd-9644-487d-9333-e95ab24cdb5d.png)

## Todo
- [x] 이슈 확인
- [x] 클라이언트에 공유

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
@paksuua  흠.. 제가 `develop`브랜치에서 `eureka`, `gateway`서버 모두 켜고 테스트한 결과 매우 잘 실행되는데 뭐가 문제인지 알수 있을까요?
혹시 Header에 `accessToken`이 빠진건 아닌지 확인 부탁드립니다.

**Comment by paksuua** [comment]
정상 동작 확인했습니다!
