### ISSUE TITLE
Friend List Get API 응답 수정 요청

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#61]
## Description
문제 상황: 수정, 차단 친구를 업데이트 하는 api에서 다음과 같이 isMarked, isHidden, isBlocked가 required이기 때문에 클라이언트에서 요청 값으로 overwrite되는 것 같은데
두번째 사진을 보면 예를들어 숨김 친구를 조회하는 경우 해당 유저들의 isMarked, idBlocked 값을 알 수 없습니다. 

## 친구 관계 수정 API의 request
<img width="601" alt="스크린샷 2022-02-10 오후 12 59 59" src="https://user-images.githubusercontent.com/43838030/153335843-c01a0420-2075-469d-835f-28efd81f88c8.png">

## 친구 리스트 조회 API response
<img width="440" alt="스크린샷 2022-02-10 오후 1 00 17" src="https://user-images.githubusercontent.com/43838030/153335848-74a77c3f-0dfd-49f2-a04a-8f546114d0f7.png">

수정 선택지는 2가지 정도가 될 것 같습니다
1. 친구 관계 수정 API에서 isMarked, isHidden, isBlocked를 nullable로 요청할 수 있도록 수정
2. 친구 리스트 조회 API에서 응답으로 위 3개의 현재 값 보내주기

## Todo
- [x] 이슈 확인
- [x] ~~api 수정~~
- [ ] wiki 업데이트

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
아직 구현하지 않은 API라서 명세서만 고치고 이슈 close 할께요~

**Comment by SuyeonChoi** [comment]
@paksuua [친구 리스트 조회](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/%EC%B9%9C%EA%B5%AC-%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EC%A1%B0%ED%9A%8C)에서 RequestParameter를 통해  `isHidden`, `isBlocked` 정보를 요청하는데 클라이언트에서 해당 데이터를 사용할 수는 없는 걸까요?
해당 데이터를 사용할 수 있다면, `isMarked`도 RequestParameter에 추가할게요.

## 친구 리스트 조회 URL 예시
![image](https://user-images.githubusercontent.com/28749734/153392069-271c4637-ac86-4428-887f-0a3e0aad5288.png)

**Comment by paksuua** [comment]
예를들어 숨김 친구를 `/api/membership/friend?isHidden=true`로 받은 경우 
response의 user들의 isBlocked 여부를 알 수 없습니다! 
따라서 숨긴 친구들의 block여부를 알기 위해서는 `/api/membership/friend?isHidden=true&isBlocked=true`라는 통신 요청을 추가로 보내야 합니다. 여기서 isMarked도 추가되면 Client에서는 하나의 원하는 요청을 위해서 3번의 중복 요청을 해야합니다!

**Comment by paksuua** [comment]
아하!! 맞네요🥳 이슈 대응 필요 없을 것 같습니다 감사합니다

**Comment by SuyeonChoi** [comment]
넵 그럼 [친구 리스트 조회](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/친구-리스트-조회)에 `isMarked`만 Request Parameter로 추가하고 이슈 Close 하겠습니다~

**Comment by SuyeonChoi** [comment]
[친구 리스트 조회](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/친구-리스트-조회) wiki 업데이트했습니다! 😎
