### ISSUE TITLE
채팅방 생성 API 오류 이슈

### ISSUE THREAD

**Issue by 014967** [DevCamp2Flame/FlameTalk_Server#64]
## Description

![Screen Shot 2022-02-10 at 16 16 02 PM](https://user-images.githubusercontent.com/62296097/153358672-4073704d-2921-406d-88cf-d7724ed967be.png)

org.springframework.orm.jpa.JpaSystemException: Error attempting to apply AttributeConverter; nested exception is javax.persistence.PersistenceException: Error attempting to apply AttributeConverter

![Screen Shot 2022-02-10 at 16 16 14 PM](https://user-images.githubusercontent.com/62296097/153358691-4df0c9d4-e38d-4435-b922-068e69d44e5d.png)

[ChatRoomService.java](http://chatroomservice.java/):80 번째 , defaultThumnail에서 문제 발생합니다

![Screen Shot 2022-02-10 at 16 19 26 PM](https://user-images.githubusercontent.com/62296097/153358708-9bf8c9ae-c828-4a79-83d9-54427117c502.png)
![Screen Shot 2022-02-10 at 16 16 20 PM](https://user-images.githubusercontent.com/62296097/153358721-aeba4b61-097c-4f4b-8473-3f7685f88225.png)

ChatRoomController.java. 36번째 줄

chatrromService에서 save가 안되는 문제입니다

![Screen Shot 2022-02-10 at 16 16 32 PM](https://user-images.githubusercontent.com/62296097/153358765-b32e04c0-a69a-4485-8c60-5bac4755c457.png)

StickerConverter에서 문제 발생합니다

![Screen Shot 2022-02-10 at 16 16 45 PM](https://user-images.githubusercontent.com/62296097/153358779-60a910ad-c713-4721-aa19-c1817650170c.png)

convertToEntityAttribute에서 문제가 발생하고 있는데,

argument “content” is null 오류 

objectMapper에서 readvalue 에서 dbData가 content입니다.

![Screen Shot 2022-02-10 at 16 21 43 PM](https://user-images.githubusercontent.com/62296097/153358795-4a92ff54-48c8-4064-88f5-de742598a04c.png)

코드만 보아서는 stickerconveter에서 dbData인자가 null값이면 안되는 것 같은데 , null이 들어가서 문제인 것 같습니다.

아래 로그 첨부합니다 

[https://nonstop-angle-860.notion.site/36a15a31241d434d8aab73e3bb460526](url)

## Todo
- [x] StickerConverter converToEntityAttribute objectMapper.readvalue에서 발생하는 문제를 확인하고 해결

## ETC
기타사항

**Comment by 014967** [comment]
Sticker는 null 허용인데... 왜 이런 오류가 발생하는지 잘모르겠습니다. 수연님 ㅠㅠ

**Comment by SuyeonChoi** [comment]
Profile의 스티커가 `null` 인 경우 발생하는 오류였군요! 😶‍🌫️😶‍🌫️😶‍🌫️
