### ISSUE TITLE
Friend List Get API 응답 수정 요청

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#83]
## Description
현재 2곳에서 친구 숨김, 차단 여부를 변경할 수 있도록 했습니다
1. 친구 프로필 상세 뷰
2. 숨김, 차단 친구 리스트 뷰
 두 접근 모두 Friend List Get API(친구 리스트 조회)를 통해 응답을 받은 후 사용자의 이벤트에 따라 api 요청을 보내고 아래와 같은 응답을 받습니다! 
![스크린샷 2022-02-12 오후 8 57 30](https://user-images.githubusercontent.com/43838030/153710355-d7760705-24cf-4898-ad65-abce08f7a0fa.png)

Profile Update API(친구 관계 수정)를 위해서는 
`assignedProfileId `이라는 친구에게 보여줄 나의 프로필 id가 필요합니다! 그러나 이 값은 친구마다 다르게 설정되어 있기 때문에 친구 리스트 조회 시 응답으로 `그 친구에게 할당된 나의 프로필 아이디`가 추가로 필요할 것 같습니다!

## Todo
- [x] 이슈확인
- [x] 수정 가능 여부 알려주기

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
- [x] Wiki 반영 [친구 리스트 조회 API](https://github.com/DevCamp2Flame/FlameTalk_Server/wiki/친구-리스트-조회)
- [x] API 업데이트

**Comment by paksuua** [comment]
응답 수정 반영하여 테스트 완료했습니다! 감사합니🥰
